### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by polotek** [tinselwear/tinsel.me#5]
- [ ] Update product copy
- [ ] #4 Generate sitemap and submit to google https://www.google.com/webmasters/tools/sitemap-list?siteUrl=http://tinsel.me/&utm_source=wnc_376106&utm_medium=gamma&utm_campaign=wnc_376106&utm_content=msg_743502&hl=en#MAIN_TAB=1&CARD_TAB=-1
- [ ] #6 Fix robots.txt to allow all crawling
